config/routes.rb
TaskApp::Application.routes.draw do

  get "tasks" => 'tasks#index', :as => :tasks
  post "tasks" => 'tasks#create' 
  #get "tasks/new" => 'tasks#new'

  get "tasks/:id" => 'tasks#show', :as => :task
  get "tasks/:id/edit" => 'tasks#edit', :as => :edit_task
  put "tasks/:id" => 'tasks#update', :as => :update_task
  delete "tasks/:id" => 'tasks#destroy'



end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @all_tasks = Task.all
    @task = Task.new
    
  end
  
  def show
    @task = Task.find params[:id]

  end
  
  def edit
    @task = Task.find params[:id]
  
  end

  def update
    @task = Task.find_by_id(params[:id])
    @task.update_attributes (params[:task])
    redirect_to task_url(@task.id)
  end
  
  def create
  
     Task.create params[:task]
     
     redirect_to tasks_url
      
   end
   
  def destroy
    
    @task =Task.find_by_id(params[:id])
        @task.destroy
        redirect_to tasks_url
    end
    
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |form|%>

<p>

<%= form.label:task%>
<%= form.text_field:task%>

</p>


<p>

     <%= form.label:priority %> 
     <%= form.text_field :priority %>
</p>

<p>

     <%= form.label:status %> 
     <%= form.text_field :status %>
</p>

<%= form.submit%>

<% end %>

app/views/tasks/edit.html.erb
<h1>Update Task</h1>

<p><%= render 'form'%></p>

app/views/tasks/index.html.erb
<h1><strong>To Do List<strong></h1>

<img src= "http://www.weirdworm.com/img/misc/10-bizarre-tattoos/to-do-list-tattoo.jpg" />
<p>
  
  <% @all_tasks.each do | x |%>
    <li> Task:  <%= x.task %> - <%= link_to "Status", "tasks/#{x.id}"%>  <%= link_to "Delete", "tasks/#{x.id}", :method => :delete%></li>
    
    
    
    <% end %>
  
</p>

</p>

<h2>Add a New Task</h2>

<%= form_for @task do | f | %> 

<p>

     <%= f.label:task %> 
     <%= f.text_field :task %>
</p>

<p>

     <%= f.label:priority %> 
     <%= f.text_field :priority %>
</p>

<p>

     <%= f.label:status %> 
     <%= f.text_field :status %>
</p>


<p><%= f.submit %></p> 


<% end %>

<img src= "http://image.shutterstock.com/display_pic_with_logo/131380/131380,1207311280,16/stock-vector-v-rose-and-snake-tattoo-tattoo-design-vector-drawing-11121589.jpg>" />

app/views/tasks/show.html.erb
<h1><%= @task.task %></h1>

<img src= "http://www.weirdworm.com/img/misc/10-bizarre-tattoos/to-do-list-tattoo.jpg" />

<ul>
  <li> Name <%= @task.task %></li>
  <li> Age <%= @task.priority %></li>
  <li> Location <%= @task.status %></li>
 <li><%= link_to "Edit", edit_task_url(@task.id)%> </li>
 <li><%= link_to "Home", tasks_url %> </li>
</ul>

app/views/tasks/update.html.erb
<h1><%= @task.task %></h1>


<ul>
  <li> Name <%= @task.task %></li>
  <li> Age <%= @task.priority %></li>
  <li> Location <%= @task.status %></li>
 

</ul>